-- PharmaSys — professional controls: server-side cancellation permissions + audit trail.
-- Apply after 20261009000200_sales_control_stock_correction_and_profit_kpis.sql.
-- Existing cancellation RPCs remain responsible for the atomic stock/cash/benefit changes.

CREATE TABLE IF NOT EXISTS public.journal_audit_pharmasys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  actor_user_id bigint,
  actor_role text,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  ticket_id text,
  reason text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_pharmasys_tenant_date
  ON public.journal_audit_pharmasys(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_pharmasys_ticket
  ON public.journal_audit_pharmasys(tenant_id, ticket_id, created_at DESC);
ALTER TABLE public.journal_audit_pharmasys ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS audit_pharmasys_admin_read ON public.journal_audit_pharmasys;
CREATE POLICY audit_pharmasys_admin_read ON public.journal_audit_pharmasys
  FOR SELECT TO anon, authenticated
  USING (tenant_id = public.current_tenant_id() AND public.is_current_admin());
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.journal_audit_pharmasys FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.journal_audit_pharmasys TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.journal_audit_pharmasys_id_seq TO anon, authenticated;

-- Status changes can be made by SECURITY DEFINER RPCs, so authorization must be
-- enforced in triggers as well as in the UI. Admin may act on any ticket; an
-- assistant may only cancel their own ticket. Other roles cannot cancel tickets.
CREATE OR REPLACE FUNCTION public.pharmasys_guard_ticket_cancellation()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_role text := lower(COALESCE(public.current_user_role(), ''));
        v_user_id bigint := public.current_user_id();
        v_tenant uuid := public.current_tenant_id();
BEGIN
  IF NEW.statut IS DISTINCT FROM OLD.statut AND upper(COALESCE(NEW.statut,'')) = 'ANNULEE' THEN
    IF v_tenant IS NULL OR NEW.tenant_id <> v_tenant THEN
      RAISE EXCEPTION 'Session invalide ou tenant non autorisé';
    END IF;
    IF v_role NOT IN ('admin','administrateur') AND NOT (v_role='assistant' AND v_user_id IS NOT NULL AND OLD.assistant_id=v_user_id) THEN
      RAISE EXCEPTION 'Annulation refusée : seuls l’administrateur ou le vendeur propriétaire du ticket peuvent annuler';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_pharmasys_guard_ticket_cancellation ON public.tickets;
CREATE TRIGGER trg_pharmasys_guard_ticket_cancellation
  BEFORE UPDATE OF statut ON public.tickets
  FOR EACH ROW EXECUTE FUNCTION public.pharmasys_guard_ticket_cancellation();

CREATE OR REPLACE FUNCTION public.pharmasys_guard_line_cancellation()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_role text := lower(COALESCE(public.current_user_role(), ''));
        v_user_id bigint := public.current_user_id();
        v_tenant uuid := public.current_tenant_id();
        v_ticket_assistant bigint;
BEGIN
  IF NEW.statut IS DISTINCT FROM OLD.statut AND upper(COALESCE(NEW.statut,'')) = 'ANNULEE' THEN
    IF v_tenant IS NULL OR NEW.tenant_id <> v_tenant THEN
      RAISE EXCEPTION 'Session invalide ou tenant non autorisé';
    END IF;
    SELECT t.assistant_id INTO v_ticket_assistant
      FROM public.tickets t
      WHERE t.id=OLD.ticket_id AND t.tenant_id=v_tenant;
    IF NOT FOUND THEN RAISE EXCEPTION 'Ticket introuvable pour cette annulation'; END IF;
    IF v_role NOT IN ('admin','administrateur') AND NOT (v_role='assistant' AND v_user_id IS NOT NULL AND v_ticket_assistant=v_user_id) THEN
      RAISE EXCEPTION 'Annulation refusée : seuls l’administrateur ou le vendeur propriétaire du ticket peuvent annuler un article';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_pharmasys_guard_line_cancellation ON public.ticket_lignes;
CREATE TRIGGER trg_pharmasys_guard_line_cancellation
  BEFORE UPDATE OF statut ON public.ticket_lignes
  FOR EACH ROW EXECUTE FUNCTION public.pharmasys_guard_line_cancellation();

-- Append-only audit events for ticket/line cancellations. The triggers run in
-- the same transaction as the cancellation, so an incomplete refund/stock update
-- rolls back both the business operation and the audit event.
CREATE OR REPLACE FUNCTION public.pharmasys_audit_ticket_status()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_action text;
BEGIN
  IF NEW.statut IS DISTINCT FROM OLD.statut THEN
    v_action := CASE WHEN upper(COALESCE(NEW.statut,''))='ANNULEE' THEN 'ANNULATION_TICKET' ELSE 'CHANGEMENT_STATUT_TICKET' END;
    INSERT INTO public.journal_audit_pharmasys(tenant_id,actor_user_id,actor_role,action,entity_type,entity_id,ticket_id,reason,before_data,after_data)
    VALUES (NEW.tenant_id, public.current_user_id(), public.current_user_role(), v_action, 'ticket', NEW.id, NEW.id,
      CASE WHEN v_action='ANNULATION_TICKET' THEN 'Annulation via flux métier' ELSE NULL END,
      jsonb_build_object('statut',OLD.statut,'montant_total',OLD.montant_total,'benefice_total',OLD.benefice_total,'nb_articles',OLD.nb_articles),
      jsonb_build_object('statut',NEW.statut,'montant_total',NEW.montant_total,'benefice_total',NEW.benefice_total,'nb_articles',NEW.nb_articles));
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_pharmasys_audit_ticket_status ON public.tickets;
CREATE TRIGGER trg_pharmasys_audit_ticket_status AFTER UPDATE OF statut ON public.tickets
  FOR EACH ROW EXECUTE FUNCTION public.pharmasys_audit_ticket_status();

CREATE OR REPLACE FUNCTION public.pharmasys_audit_line_status()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NEW.statut IS DISTINCT FROM OLD.statut THEN
    INSERT INTO public.journal_audit_pharmasys(tenant_id,actor_user_id,actor_role,action,entity_type,entity_id,ticket_id,reason,before_data,after_data)
    VALUES (NEW.tenant_id, public.current_user_id(), public.current_user_role(),
      CASE WHEN upper(COALESCE(NEW.statut,''))='ANNULEE' THEN 'ANNULATION_LIGNE_TICKET' ELSE 'CHANGEMENT_STATUT_LIGNE' END,
      'ticket_ligne', NEW.id::text, NEW.ticket_id,
      CASE WHEN upper(COALESCE(NEW.statut,''))='ANNULEE' THEN 'Annulation via flux métier' ELSE NULL END,
      jsonb_build_object('statut',OLD.statut,'produit_id',OLD.produit_id,'nom',OLD.nom,'quantite',OLD.quantite,'total',OLD.total,'profit',OLD.profit),
      jsonb_build_object('statut',NEW.statut,'produit_id',NEW.produit_id,'nom',NEW.nom,'quantite',NEW.quantite,'total',NEW.total,'profit',NEW.profit));
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_pharmasys_audit_line_status ON public.ticket_lignes;
CREATE TRIGGER trg_pharmasys_audit_line_status AFTER UPDATE OF statut ON public.ticket_lignes
  FOR EACH ROW EXECUTE FUNCTION public.pharmasys_audit_line_status();

-- Indexes support tenant-scoped lookups used by reconciliation and report pages.
CREATE INDEX IF NOT EXISTS idx_tickets_tenant_date_status
  ON public.tickets(tenant_id, date, statut);
CREATE INDEX IF NOT EXISTS idx_ticket_lignes_tenant_ticket_status
  ON public.ticket_lignes(tenant_id, ticket_id, statut);
CREATE INDEX IF NOT EXISTS idx_paiements_tenant_ticket_nature
  ON public.paiements(tenant_id, ticket_id, nature);
CREATE INDEX IF NOT EXISTS idx_caisse_tenant_ticket_nature
  ON public.mouvements_caisse(tenant_id, ticket_id, nature);

COMMENT ON TABLE public.journal_audit_pharmasys IS
  'Journal append-only des changements de statut de tickets et lignes; lecture réservée à l’administrateur du tenant.';
